
/* ** FIELD TABLES ** */

/*

Media Information table

 */
CREATE TABLE LUM_MD_MEDIA_INFO(
	UOI_ID nvarchar(40) NOT NULL,
	MEDIA_TITLE nvarchar(250) NULL,
	MASTER_FILE_NAME nvarchar(250) NULL,
	ASSET_TYPE nvarchar(50) NULL,
	BRAND nvarchar(10) NULL,
	LANGUAGES nvarchar(5) NULL,
	PACKAGING_CLUSTERS nvarchar(50) NULL,
	DESCRIPTION nvarchar(500) NULL,
	KEYWORDS nvarchar(800) NULL,
	ALERT_COMMENT nvarchar(50) NULL,
	LEGEND nvarchar(100) NULL
);

ALTER TABLE LUM_MD_MEDIA_INFO  
WITH CHECK ADD CONSTRAINT LUM_MD_MEDIA_INFO_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_MEDIA_INFO CHECK CONSTRAINT LUM_MD_MEDIA_INFO_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_MEDIA_INFO','N',NULL);

/*
Media Info Tabular table
*/
CREATE TABLE LUM_MD_MEDIA_INFO_TAB(
	UOI_ID nvarchar(40) NOT NULL,
	REGIONS nvarchar(20) NULL,
	COUNTRIES nvarchar(500) NULL
);

ALTER TABLE LUM_MD_MEDIA_INFO_TAB  
WITH CHECK ADD CONSTRAINT LUM_MD_MEDIA_INFO_TAB_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_MEDIA_INFO_TAB CHECK CONSTRAINT LUM_MD_MEDIA_INFO_TAB_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_MEDIA_INFO_TAB','Y',NULL);
/*
Visual, Music, Approval Rights
*/

--Visual Rights
CREATE TABLE LUM_MD_USAGE_RIGHTS_TAB(
	UOI_ID nvarchar(40) NOT NULL,
	COPYRIGHT_VISUAL_APPLICABLE nvarchar(5) NULL,
	COPYRIGHT_TOUCHPOINTS nvarchar(100) NULL,
	COPYRIGHT_START_DATE datetime NULL,
	COPYRIGHT_END_DATE datetime NULL,
	COPYRIGHT_GEO_LOCATION nvarchar(100) NULL,
	COPYRIGHT_SUPPLIER nvarchar(100) NULL
);

ALTER TABLE LUM_MD_USAGE_RIGHTS_TAB
WITH CHECK ADD CONSTRAINT LUM_MD_USAGE_RIGHTS_TAB_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_USAGE_RIGHTS_TAB CHECK CONSTRAINT LUM_MD_USAGE_RIGHTS_TAB_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_USAGE_RIGHTS_TAB','Y',NULL);

--Music Rights
CREATE TABLE LUM_MD_MUSIC_RIGHTS_TAB(
	UOI_ID nvarchar(40) NOT NULL,
	COPYRIGHT_MUSIC_APPLICABLE nvarchar(5) NULL, 
	COPYRIGHT__MUSIC_START_DATE datetime NULL,
	COPYRIGHT_MUSIC_END_DATE datetime NULL
);

ALTER TABLE LUM_MD_MUSIC_RIGHTS_TAB
WITH CHECK ADD CONSTRAINT LUM_MD_MUSIC_RIGHTS_TAB_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_MUSIC_RIGHTS_TAB CHECK CONSTRAINT LUM_MD_MUSIC_RIGHTS_TAB_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_MUSIC_RIGHTS_TAB','Y',NULL);

--Approval Rights
CREATE TABLE LUM_MD_APPROVAL_RIGHTS_TAB(	
	UOI_ID nvarchar(40) NOT NULL,
	APPROVED_BY_BRAND nvarchar(100) NULL,
	APPROVER_NAME nvarchar(100) NULL,
	APPROVAL_DATE datetime NULL
);

ALTER TABLE LUM_MD_APPROVAL_RIGHTS_TAB
WITH CHECK ADD CONSTRAINT LUM_MD_APPROVAL_RIGHTS_TAB_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_APPROVAL_RIGHTS_TAB CHECK CONSTRAINT LUM_MD_APPROVAL_RIGHTS_TAB_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_APPROVAL_RIGHTS_TAB','Y',NULL);

/*
File Information
*/

CREATE TABLE LUM_MD_FILE_INFO_TAB(
	UOI_ID nvarchar(40) NOT NULL,
	ACTIVATION_DATE datetime NULL,
	DEACTIVATION_DATE datetime NULL,
	CREATOR_OWNER_GROUP nvarchar(50) NULL	
);

ALTER TABLE LUM_MD_FILE_INFO_TAB
WITH CHECK ADD CONSTRAINT LUM_MD_FILE_INFO_TAB_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_FILE_INFO_TAB CHECK CONSTRAINT LUM_MD_FILE_INFO_TAB_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_FILE_INFO_TAB','Y',NULL);


CREATE TABLE LUM_MD_FILE_INFO(
	UOI_ID nvarchar(40) NOT NULL,
	CONTENT_EDITOR nvarchar(50) NULL,
	LEGACY_OWNER_EMAIL nvarchar(50) NULL
);


ALTER TABLE LUM_MD_FILE_INFO
WITH CHECK ADD CONSTRAINT LUM_MD_FILE_INFO_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_FILE_INFO CHECK CONSTRAINT LUM_MD_FILE_INFO_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_FILE_INFO','N',NULL);

/*
Administrative Information
*/

CREATE TABLE LUM_MD_ADMIN_INFO(
	UOI_ID nvarchar(40) NOT NULL,
	MIGRATION_STATUS nvarchar(30) NULL, --* field length are assumed
	IMPORTED_DATE datetime NULL,
	LEGACY_CLASSIFICATION nvarchar(50) NULL
);

ALTER TABLE LUM_MD_ADMIN_INFO 
WITH CHECK ADD CONSTRAINT LUM_MD_ADMIN_INFO_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_ADMIN_INFO CHECK CONSTRAINT LUM_MD_ADMIN_INFO_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_ADMIN_INFO','N',NULL);

--PENDING SECURITY table

/*
 Industrial
*/
CREATE TABLE LUM_MD_INDUSTRIAL_INFO(
	UOI_ID nvarchar(40) NOT NULL,
	REGULATION nvarchar(50) NULL,
	TEST_HOUSE nvarchar(50) NULL,
	MANUFACTURER nvarchar(50) NULL,
	AUTHORITY nvarchar(50) NULL,
	APPROVER_COUNTRY nvarchar(50) NULL,
	E_MARK nvarchar(50) NULL,
	EXTENSION_NUMBER nvarchar(10) NULL,
	INDUSTRIAL_STANDARD nvarchar(50) NULL,
	INDUSTRIAL_STANDARD_NUMBER nvarchar(50) NULL,
	YEAR_OF_RELEASE nvarchar(4) null,
	TYPE_TEST nvarchar(50) NULL,
	TEST_TIME_PERIOD nvarchar(8) NULL,
	PPAP_NUMBER numeric(5) NULL,
	PPAP_LEVEL nvarchar(10) NULL,
	PROJECT_NUMBER numeric NULL,
	PCN_NUMBER numeric NULL
);

ALTER TABLE LUM_MD_INDUSTRIAL_INFO
WITH CHECK ADD CONSTRAINT LUM_MD_INDUSTRIAL_INFO_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_INDUSTRIAL_INFO CHECK CONSTRAINT LUM_MD_INDUSTRIAL_INFO_FK;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_INDUSTRIAL_INFO','N',NULL);


/*
Product Information
*/

CREATE TABLE LUM_MD_PRODUCT_INFO(
	UOI_ID nvarchar(40) NOT NULL,
	PRODUCT_TYPE nvarchar(30) NULL
);

ALTER TABLE LUM_MD_PRODUCT_INFO
WITH CHECK ADD CONSTRAINT LUM_MD_PRODUCT_INFO_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_PRODUCT_INFO CHECK CONSTRAINT LUM_MD_PRODUCT_INFO_FK;


/*
Customer Information
*/

CREATE TABLE LUM_MD_CUSTOMER_INFO_TAB(
	UOI_ID nvarchar(40) NOT NULL,
	SOLD_TO_CUSTOMER nvarchar(500) NULL
);

ALTER TABLE LUM_MD_CUSTOMER_INFO_TAB
WITH CHECK ADD CONSTRAINT LUM_MD_CUSTOMER_INFO_TAB_FK FOREIGN KEY(UOI_ID)
REFERENCES UOIS (UOI_ID) ON DELETE CASCADE;

ALTER TABLE LUM_MD_CUSTOMER_INFO_TAB CHECK CONSTRAINT LUM_MD_CUSTOMER_INFO_TAB_FK;

Alter table LUM_MD_CUSTOMER_INFO_TAB alter column SOLD_TO_CUSTOMER nvarchar(500) null;

INSERT INTO METADATA_TABLE_INCLUSIONS VALUES ('LUM_MD_CUSTOMER_INFO_TAB','Y',NULL);

/* ***********
*
*
 LOOKUP TABLES
*
*
*
 *************/
--ASSET TYPE
CREATE TABLE LUM_MD_ASSET_TYPE_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_ASSET_TYPE_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);
 
-- BRAND
CREATE TABLE LUM_MD_BRAND_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_BRAND_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

-- LANGUAGES
CREATE TABLE LUM_MD_LANGUAGES_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_LANGUAGES_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

-- REGIONS
CREATE TABLE LUM_MD_REGIONS_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_REGIONS_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

-- YES NO lookup for Copyright visual applicable and copyright music applicable.
-- More fields can make use of the OOB lookup if the lookup values are Yes/No only

--Creator Owner Cascading Group
CREATE TABLE LUM_MD_CREATOR_OWNER_LU1(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_CREATOR_OWNER_LU1_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

CREATE TABLE LUM_MD_CREATOR_OWNER_LU2(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_CREATOR_OWNER_LU2_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

CREATE TABLE LUM_MD_CREATOR_OWNER_CAS_MAP(
	CODE nvarchar(2000) NOT NULL,
	CREATOR_OWNER_LEVEL1 nvarchar(2000) NULL,
	CREATOR_OWNER_LEVEL2 nvarchar(2000) NULL,
 CONSTRAINT L_MD_CREATOR_OWNER_CAS_MAP_PK PRIMARY KEY CLUSTERED 
(
	CODE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

--Indutrial Standard
CREATE TABLE LUM_MD_INDUSTRIAL_STANDARD_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_INDUSTRIAL_STANDARD_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

--Product Grouping
CREATE TABLE LUM_MD_PRODUCT_GROUPING_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_PRODUCT_GROUPING_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

--Type Test
CREATE TABLE LUM_MD_TYPE_TEST_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_TYPE_TEST_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

--PPAP LEVEL
CREATE TABLE LUM_MD_PPAP_LEVEL_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_PPAP_LEVEL_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

--Factory
CREATE TABLE LUM_MD_FACTORY_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_FACTORY_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

--Year of RELEASE
CREATE TABLE LUM_MD_YEAR_OF_REL_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_YEAR_OF_REL_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_YEAR_OF_REL_LU');

-- Packaging Clusters
CREATE TABLE LUM_MD_PKG_CLUSTER_LU1(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_PKG_CLUSTER_LU1_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_PKG_CLUSTER_LU1');

CREATE TABLE LUM_MD_PKG_CLUSTER_LU2(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_PKG_CLUSTER_LU2_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_PKG_CLUSTER_LU2');

CREATE TABLE LUM_MD_PKG_CLUSTER_CAS_MAP(
	CODE nvarchar(2000) NOT NULL,
	PKG_CLUSTER_LEVEL1 nvarchar(2000) NULL,
	PKG_CLUSTER_LEVEL2 nvarchar(2000) NULL,
 CONSTRAINT LUM_MD_PKG_CLUSTER_CAS_MAP_PK PRIMARY KEY CLUSTERED 
(
	CODE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

/*
Test Time Period
*/

CREATE TABLE LUM_MD_TEST_TIME_LU1(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_TEST_TIME_LU1_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_TEST_TIME_LU1');

CREATE TABLE LUM_MD_TEST_TIME_LU2(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_TEST_TIME_LU2_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_TEST_TIME_LU2');

--Create Lookup domain from Metadata Editor

CREATE TABLE LUM_MD_TEST_TIME_CAS_MAP(
	CODE nvarchar(2000) NOT NULL,
	TEST_TIME_LEVEL1 nvarchar(2000) NULL,
	TEST_TIME_LEVEL2 nvarchar(2000) NULL,
 CONSTRAINT LUM_MD_TEST_TIME_CAS_MAP_PK PRIMARY KEY CLUSTERED 
(
	CODE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

/*

SOLD TO CUSTOMER

*/

CREATE TABLE LUM_MD_SOLD_TO_BANNER_LU(
	ID nvarchar(40) NOT NULL,
	VALUE nvarchar(40) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_SOLD_TO_BANNER_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_SOLD_TO_BANNER_LU');

CREATE TABLE LUM_MD_SOLD_TO_PARTY_LU(
	ID nvarchar(80) NOT NULL,
	VALUE nvarchar(80) NOT NULL,
	DESCRIPTION nvarchar(200) NULL,
	CONSTRAINT LUM_MD_SOLD_TO_PARTY_LU_PK PRIMARY KEY CLUSTERED 
(
	ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

INSERT INTO LOOKUP_TABLE_INCLUSIONS values ('LUM_MD_SOLD_TO_PARTY_LU');

--Create Lookup domain from Metadata Editor

CREATE TABLE LUM_MD_SOLD_TO_CUS_CAS_MAP(
	CODE nvarchar(2000) NOT NULL,
	SOLD_TO_BANNER nvarchar(2000) NULL,
	SOLD_TO_PARTY nvarchar(2000) NULL,
 CONSTRAINT LUM_MD_SOLD_TO_CUS_CAS_MAP_PK PRIMARY KEY CLUSTERED 
(
	CODE ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

create table LUMILEDS_MIGRATION_PAL_OTMM_MAPPING (
	PAL_FIELD nvarchar(50),
	OTMM_FIELD nvarchar(30)
);
